var express = require('express'),
    app = express(),
    fs = require('fs');

app.set('port', (process.env.PORT || 80))
app.use(express.static(__dirname))

app.get('/about',function(req,res){
    res.send([
        {"Id":"0","Name":"Keshor Mahalingam","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"1","Name":"Panneer Dhamodharan","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"2","Name":"Rekha Rajendran","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"3","Name":"Anjanadevi Kannan","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"4","Name":"Dhinesh Viswanathan","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"5","Name":"Thirunavukkarasu Muthuswamy","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"6","Name":"Kavitha Iyer","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"7","Name":"Sathees Sadhanatham","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"8","Name":"Janani Gopalakrishnan","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"}, 
        {"Id":"9","Name":"Mariselvi Santhanam","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"10","Name":"Bhuvanesh KV","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"},
        {"Id":"11","Name":"Arun Subramaniyan","Picture":"profile.jpg","Special":"The Speedster.This frontline runner not only runs fast, but also talks fast.","First_Step":"Started running in the year 2008 and since then there has been no looking back.","Recent_Accomplishments":"Ran about 323 Kms. in the month of March 2013. Started off with 13X13 run and then continued the momentum till the end of the month","Frequency":"3-4 runs a week, followed by a long run 19-25K on weekends","Why_Run":"Started off as fun, but got hooked on to running when I discovered my ability to run 21 km. I can run alone anytime anywhere, but of course, it is always fun to run with The_Team!","Motivation_to_Run":"Running makes me feel fit and look much younger compared to peers of same age.","Favourite_Route":"Running along the Elliots beach, in and around Adyar, Kotturpuram and IIT.","The_Team":"Dream runners as a group, means everything to me in fitness. Known for our punctual runs, we have been a benchmark and inspiration to many people in Besant Nagar"}        
    ]);
});

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'))
});